//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFCNMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmail
    {
        public int ID { get; set; }
        public Nullable<int> CareGiverID { get; set; }
        public string EMail { get; set; }
        public Nullable<int> EmailType { get; set; }
    
        public virtual tblPrimaryCaregiverdata tblPrimaryCaregiverdata { get; set; }
    }
}
